### PR TITLE
Make PlayHelper able to handle only a VJoyDevice on player 2

### PR DESCRIPTION
**Pull request by WesselKroos**
I was unable to only use player 2 in the VJoy configuration so I've changed the PlayHelper.py so it doesn't brake anymore. This makes me able to play against my bot in exhibition mode

### CODE REVIEW

**Comment by tarehart** [comment]
Thanks for contributing!

This shouldn't stop us from accepting the pull request, but I want to point out that this conflicts with the own-controller branch, which we apparently never merged in to master.

**Comment by tarehart** [comment]
We opted to merge in own-controller first, so now you're stuck with the conflict resolution, sorry. On the bright side, your change should require less code now, if it's even still necessary at all.

**Comment by drssoccer55** [comment]
Yupp looks like this issue will also happen with the latest changes and needs to be fixed.  Code always assumes 2 vjoy controllers exist which is a bad assumption.

**Comment by drssoccer55** [comment]
@tarehart I believe with your last code change this is taken care of.  We can close this now right?

**Comment by tarehart** [comment]
I think there's still a weird spot here: https://github.com/drssoccer55/RLBot/blob/master/PlayHelper.py#L6

If the user has only one vJoy device configured, and chooses to disable p1 and enable p2 in rlbot.cfg, I imagine this code will break.

I think we can still close this though, since playing against your bot in exhibition mode is pretty easy at this point. (Just have 2 vjoy controllers configured, and disable one of the players in rlbot.cfg)

**Pull request closed without merging**
